name: titanic
dependencies:
- pandas=0.23.4
- python=3.6
- pip:
  - zappa==0.47.0
  - flask==1.0.2
  - scikit-learn==0.20
  - cython==0.28.5
  - notebook==5.5.0
  - matplotlib==3.0.0
  - pytest==3.9.1
  - kaggle